### ISSUE TITLE
Discussion of the pulse values in timer 1 Output Compare mode.

### ISSUE THREAD

**Issue by Mohamed-Sedeek** [PionixPublic/yeti-firmware#2]
Hi sir,
This is not to report an issue but to discuss something that I don't fully understand.
I understand that we need to read both the low and high sides of the control pilot signal, and to do so you used Output Compare in order to generate an interrupt at the beginning and end of the PWM period if I understood correctly. So, if this is the case, I have a question regarding the (sConfigOC.Pulse) values, you used 200 and 45500 to generate interrupts at the beginning and end of the PWM signal respectively, but why did you use these values exactly? Did these values come from a certain equation or something? And if they were just to generate interrupts at the beginning and end, why not use values closer to the limits to ensure interrupt occurs at the high and low sides correctly, for instance 10 and 47990 or any other values closer to the limits?

**Comment by corneliusclaussen** [comment]
Hi Mohamed,

your understanding is correct, this is to trigger the ADC at the correct time when the voltage is high/low. If the signal would be an ideal square wave, you are also right that the ADC should trigger very close to the PWM edges.

In real life, this is a 24V sweep (+-12V) with some capacitance on it and limited current supply, which will generate somewhat "rounded" edges. The norm says this should be designed for <2 micro seconds rise time, but the connected EV may have more capacitance on the wire deforming the signal even further.

No if you start the ADC very early (e.g. 10), the signal may still be rising and you will measure a voltage much lower than the actual high voltage. This is fatal, since you may detect a state B when there was A. Let's say the minimum PWM that it needs to work with is 4% (acutally 5% with some margin). Then the high cycle is 40us only, and you will need to wait for the signal to completely rise and fit the complete ADC conversion time in that timeframe. Another problem is interupt timing jitter, depending on priorities etc. So the ADC may sometimes start a little later then requested, and if it is still sampling while the signal is already falling again you will also get a too low voltage.

Now you could argue to make the ADC as fast as possible, which makes timing easier. The signal on the ADC is quite high impedance though and there can be significant noise from the car and environment on that signal. That means you want to sample as long as possible to get noise down.

With the low measurement it is a little bit less critical as there is a longer time when the signal is low. 

Now this needs to be 100% correct, otherwise your whole charger will not work correctly. 

What we did here is manual fine tuning: When the ADC starts, we set an extra GPIO to high and when it stops we set the GPIO to low. Then we monitor the CP signal as well as this GPIO on a scope and you can see which part of the signal is sampled. Then adjust timings such that it always samples fully high or fully low and never over edges. 
This is where the odd values are coming from that you found in the code.
That also means they are specifically tuned for this hardware and ADC clocks and might be different when changing anything.

As another measure to get stability here we also average over several pulses so that even single pulse read at the wrong time won't be a problem. As I said this is super crucial to get it right, I have seen a lot of unstable chargers simply because the ADC timing is wrong.

Best

Cornelius

**Comment by Mohamed-Sedeek** [comment]
Dear Cornelius,
First of all thank you so much for answering my questions, now I fully
understand what you did and how you got those values, and I'll try to do
the same in my project. I also want to say that I admire the amazing effort
you've put into this project, and I'm learning so much from it at the time.
Best regards.
Mohamed
